// <auto-generated />
namespace SpeedyWheelz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class firstlastname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstlastname));
        
        string IMigrationMetadata.Id
        {
            get { return "202303112142339_firstlastname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
